### PR TITLE
Automatically compact DB

### LINKED ISSUE #433: Rebuilding events table is extremely slow
**Describe the bug**
After downloading and unpacking a pruned snapshot from the snapshot server resulting in a 902 GB datadir, using `--db.migration.mode rebuild --db.preset ldb-1` is extremely slow once the `events` table is reached and becomes progressively slower.

During the first minute of migration approximately 52000 files were written to disk. After 36 hours a mere 287 files were written to disk within a minute.

The opera process continuously uses one CPU core during the operation. 1.5 million ~10KB files have been written to `chaindata/leveldb-fsh/events` so far.

**To Reproduce**
1. Unpack a snapshot (which is in `legacy-ldb` format, I believe)
2. Run opera with `--db.migration.mode rebuild --db.preset ldb-1`
3. Once the migration reaches the `gossip/e` table, after a while write speeds do not exceed 70 KB/sec (measured by `du -s` at 1 minute intervals, dividing the result by `60`).

**Expected behavior**
The release notes mention speeds around 100GB/h, i.e. 27 MB/sec

**Desktop (please complete the following information):**
- opera v1.1.2-rc.5
- FreeBSD 13.1
- go 1.18.5 and 1.19.6 have been tried
- There is a lot of free space on the NVMe SSD
- Several CPU cores are unused

**Additional context**
```
INFO [02-27|14:19:28.322] Compacting DB                            name=gossip/Lt                        until=FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF04
INFO [02-27|14:21:21.526] Transforming DB layout                   db="gossip/!"
INFO [02-27|14:21:26.893] Transforming DB layout                   db=gossip/#
INFO [02-27|14:21:30.072] Transforming DB layout                   db=gossip/$
INFO [02-27|14:21:54.665] Transforming DB layout                   db=gossip/%
INFO [02-27|14:22:56.778] Transforming DB layout                   db=gossip/&
INFO [02-27|14:23:02.854] Transforming DB layout                   db=gossip/(
INFO [02-27|14:23:08.590] Transforming DB layout                   db=gossip/*
INFO [02-27|14:24:08.412] Transforming DB layout                   db=gossip/@
INFO [02-27|14:25:13.834] Transforming DB layout                   db=gossip/B
INFO [02-27|14:27:28.153] Compacting DB                            name=gossip/B                         until=end
INFO [02-27|14:27:47.613] Transforming DB layout                   db=gossip/D
INFO [02-27|14:28:09.477] Transforming DB layout                   db=gossip/M
INFO [02-27|14:59:07.354] Compacting DB                            name=gossip/M                         until=FFFF
INFO [02-27|15:00:07.354] Compacting DB                            name=gossip/M                         until=FFFF
INFO [02-27|15:00:19.040] Transforming DB layout                   db=gossip/P
INFO [02-27|15:00:33.197] Transforming DB layout                   db=gossip/U
INFO [02-27|15:00:36.251] Transforming DB layout                   db=gossip/V
INFO [02-27|15:00:42.005] Transforming DB layout                   db=gossip/X
INFO [02-27|15:01:26.150] Transforming DB layout                   db=gossip/^
INFO [02-27|15:01:33.450] Transforming DB layout                   db=gossip/_
INFO [02-27|15:01:41.855] Transforming DB layout                   db=gossip/b
INFO [02-27|15:04:32.875] Compacting DB                            name=gossip/b                         until=end
INFO [02-27|15:05:30.638] Transforming DB layout                   db=gossip/e
<< has been at it for 36 hours >>
```

invocation:
```
     bin/opera                                   \
       --genesis     /svc/fantom/var/mainnet.g   \
       --datadir     /svc/fantom/var/            \
       --cache       20000                       \
       --v5disc                                  \
       --maxpeers    150                         \
       --http                                    \
       --http.api    txpool,eth                  \
       --http.addr   0.0.0.0                     \
       --http.vhosts '*'                         \
       --ws                                      \
       --ws.api      txpool,eth                  \
       --ws.origins  '*'                         \
       --syncmode    snap                        \
       --unlock     {{redacted}}         \
       --password    /svc/fantom/var/geth.pass  \
       --allow-insecure-unlock  \
       --verbosity 3 \
       --gcmode full \
       --db.migration.mode rebuild \
       --db.preset ldb-1
```

### PR DESCRIPTION
**Pull request by uprendis**
- automatically compact DB during genesis processing, legacy migration and DB transformation in order to avoid compaction-related performance issues during data insertion

Fix #433

### CODE REVIEW

File: cmd/opera/launcher/db-transform.go [hunk 1]
```diff
@@ -264,7 +264,7 @@ func transformComponent(datadir string, dbTypes, tmpDbTypes map[multidb.TypeName
 					return err
 				}
 				toMove[dbLocatorOf(e.New)] = true
-				newDB = batched.Wrap(newDB)
+				newDB = batched.Wrap(autocompact.Wrap(autocompact.Wrap(newDB, 1*opt.GiB), 16*opt.GiB))
```
Comment (hadv) [inline cmd/opera/launcher/db-transform.go]: Can you explain why we always need to double wrap with difference `limit` like this?

File: utils/dbutil/autocompact/store.go [hunk 2]
```diff
@@ -0,0 +1,124 @@
...
+		return nil
+	}
+	return &Batch{
+		Batch:   batch,
+		onWrite: s.onWrite,
+	}
+}
+
+func (s *Batch) Put(key []byte, value []byte) error {
+	s.written += uint64(len(key) + len(value) + 64)
```
Comment (cyberbono3) [inline utils/dbutil/autocompact/store.go]: Can you explain, please, why you add up 64 here?

Comment (uprendis) [reply utils/dbutil/autocompact/store.go]: Storage overheads, related to adding/deleting a record, wouldn't be only proportional to length of key and value. E.g. if one adds 10 records with length of `2`, it will be more expensive than 1 record with length `20`
Now, `64` wasn't really calculated but is rather a guesstimation

File: cmd/opera/launcher/db-transform.go (hunk 1 above)
Comment (uprendis) [reply cmd/opera/launcher/db-transform.go]: So that we it would automatically compact every 1 GB of added AND every 16 GB of inserted data

**Comment by uprendis** [comment]
Added constraints for `autocompact` in order to prevent an accidental misuse. Now, it only allows monotonic datasets (or series of monotonic datasets). In a case if input keys aren't monotonic, it prints a warning and disables auto-compaction for the DB instance

**Comment by cyberbono3** [comment]
> Added constraints for `autocompact` in order to prevent an accidental misuse. Now, it only allows monotonic datasets (or series of monotonic datasets). In a case if input keys aren't monotonic, it prints a warning and disables auto-compaction for the DB instance

It would be great to add some test coverage as some complexity has been introduced
